
package clientSoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EAgendaFacadeBeanWSSoapService", targetNamespace = "http://ejb/", wsdlLocation = "http://localhost:8080/pra2WSSoap/WSEAgendaSoap?wsdl")
public class EAgendaFacadeBeanWSSoapService
    extends Service
{

    private final static URL EAGENDAFACADEBEANWSSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException EAGENDAFACADEBEANWSSOAPSERVICE_EXCEPTION;
    private final static QName EAGENDAFACADEBEANWSSOAPSERVICE_QNAME = new QName("http://ejb/", "EAgendaFacadeBeanWSSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pra2WSSoap/WSEAgendaSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EAGENDAFACADEBEANWSSOAPSERVICE_WSDL_LOCATION = url;
        EAGENDAFACADEBEANWSSOAPSERVICE_EXCEPTION = e;
    }

    public EAgendaFacadeBeanWSSoapService() {
        super(__getWsdlLocation(), EAGENDAFACADEBEANWSSOAPSERVICE_QNAME);
    }

    public EAgendaFacadeBeanWSSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EAGENDAFACADEBEANWSSOAPSERVICE_QNAME, features);
    }

    public EAgendaFacadeBeanWSSoapService(URL wsdlLocation) {
        super(wsdlLocation, EAGENDAFACADEBEANWSSOAPSERVICE_QNAME);
    }

    public EAgendaFacadeBeanWSSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EAGENDAFACADEBEANWSSOAPSERVICE_QNAME, features);
    }

    public EAgendaFacadeBeanWSSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EAgendaFacadeBeanWSSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EAgendaFacadeRemoteWSSoap
     */
    @WebEndpoint(name = "WSEAgendaSoapPort")
    public EAgendaFacadeRemoteWSSoap getWSEAgendaSoapPort() {
        return super.getPort(new QName("http://ejb/", "WSEAgendaSoapPort"), EAgendaFacadeRemoteWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EAgendaFacadeRemoteWSSoap
     */
    @WebEndpoint(name = "WSEAgendaSoapPort")
    public EAgendaFacadeRemoteWSSoap getWSEAgendaSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb/", "WSEAgendaSoapPort"), EAgendaFacadeRemoteWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EAGENDAFACADEBEANWSSOAPSERVICE_EXCEPTION!= null) {
            throw EAGENDAFACADEBEANWSSOAPSERVICE_EXCEPTION;
        }
        return EAGENDAFACADEBEANWSSOAPSERVICE_WSDL_LOCATION;
    }

}
