
package clientSoap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EAgendaFacadeRemoteWSSoap", targetNamespace = "http://ejb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EAgendaFacadeRemoteWSSoap {


    /**
     * 
     * @return
     *     returns java.util.List<clientSoap.CategoryTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllCategories", targetNamespace = "http://ejb/", className = "clientSoap.ListAllCategories")
    @ResponseWrapper(localName = "listAllCategoriesResponse", targetNamespace = "http://ejb/", className = "clientSoap.ListAllCategoriesResponse")
    public List<CategoryTO> listAllCategories();

}
